### PR TITLE
Functionality for editing bikes and docks

### PR DESCRIPTION
**Pull request by jcurtiss**
@daotoo @seancavanaugh 

I will deploy this and if you guys can test it out quick that'd be sweet

edit: Deployed to our app

### CODE REVIEW

**Comment by seancavanaugh** [comment]
Creating a Bike should set the dockID to be null

Creating a Dock should set the bikeID to be null

**Comment by jcurtiss** [comment]
@seancavanaugh Updated, that should now be the behavior

**Comment by seancavanaugh** [comment]
Yup, looks great. +1

**Comment by daotoo** [comment]
:+1:

**Pull request merged**
