### PR TITLE
Populating error report

### PR DESCRIPTION
**Pull request by seancavanaugh**
There is now an end point for the PI people  to log an error by sending a stack trace and dock ID to the server.

On the server side, instead of just returning the stack trace if an error occured we will now log the message and return a flat 500. We might add additional error checking and the resulting status codes (400/401) if we have time.

@jeremycurtiss-wf everything should be ready for you to create the UI for this.

### CODE REVIEW

**Comment by seancavanaugh** [comment]
@jcurtiss  @daotoo Any comments?

**Comment by jcurtiss** [comment]
Was just testing out some of this with the UI, looks to all work as expected

**Comment by daotoo** [comment]
Code looks fine, only thing that was holding me back was the testing, but it appears it works correctly according to Jeremy.

**Comment by seancavanaugh** [comment]
Yeah, I manually tested CreateErrorReport and FindAllErrorReport and those were fine, I did some quick testing of some of the other methods and everything seems okay. I think any issues we have there will be minor.

**Comment by daotoo** [comment]
+1 from me

**Pull request merged**
