### PR TITLE
Renamed endpoints and added update methods

### PR DESCRIPTION
**Pull request by seancavanaugh**
Renamed all the endpoints to create a better design

setdocklocation and setBikeDamage, were replaced with the ability to update a dock and bike

We can probably remove the Admin model and endpoints

@daotoo  @jcurtiss 

@brnsmns13  Feel free to merge this when it won't conflict with a demo and everything is good

### CODE REVIEW

**Comment by seancavanaugh** [comment]
@jcurtiss @daotoo @brnsmns13 Hey guys, I plan on working on the code tonight. Please try to review the code by tonight, otherwise I'm just going to merge away.

**Comment by daotoo** [comment]
`app/public/js/server.js` will need to be updated to reflect these changes otherwise none of the pages are going to load. I think something like this now? @jcurtiss should be able to confirm this.

```
return {
                AddBikes: $resource('/api/bike'),
                AddDocks: $resource('/api/dock'),
                BikeDamage: $resource('/api/setbikedamage'), --- /bike/:bikeID??
                Bikes: $resource('/api/bike'),
                Docks: $resource('/api/dock'),
                ErrorReport: $resource('/api/errorreport'),
                Transactions: $resource('/api/transaction')
            }
```

`api/setbikedamage` has been removed, so @jcurtiss will have to update how locking/unlocking works now. Now that everything is basically just `/bike` or `/dock` etc, how does angular know whether the urls its hitting is a `GET`, `POST`, or `PUT`? Something I was curious about.

You have it set up so that you can only update a bike by its id. I would imagine we would want to also be able to update multiple bikes at once? Use case would be its 3am or something and no one should be able to unlock a bike, so the admin can lock all the bikes at once.

Everything else seemed like it was okay. I was able to hit multiple endpoints, checkout, checkin etc without any issues. I deployed a test branch to our app with the updates (besides the setbikedamage endpoint) to server.js, just so I could see the pages load correctly and try some things. I would suggest going there and trying some things to see what else is broken or needs to be fixed.

I think it would be best to have all the fixes (both the ui and these changes) to go in at once to ensure everything is functioning properly. Branch of this branch to continue working on other stuff I would say. Wouldn't really be a point in merging this to master yet since its not complete.

**Comment by seancavanaugh** [comment]
I don't think we need a batch update functionality, the client can update as many times as they see fit. It terms of your use case, it'd make more sense to add an additional check to check out.

Yeah, I guess branching off this makes sense. Do we have an idea of when the UI stuff will be done @jcurtiss?

**Comment by jcurtiss** [comment]
@seancavanaugh Will work on that ui stuff today

**Comment by jcurtiss** [comment]
@seancavanaugh I have finished updated the front end with these new endpoints. This code is deployed to our main site. In another pull request I will do the editing of bikes and docks.

**Comment by seancavanaugh** [comment]
@jcurtiss I'm a little curious as to why Bikes have lock/unlock. It seems like that functionality should be on the docks? Either way, can we use a modal instead of the alert for that?

**Comment by daotoo** [comment]
@seancavanaugh Wouldn't bikes have lock/unlock for when they need maintenance? That was the intent we had originally at least.

**Comment by seancavanaugh** [comment]
My reasoning is that you can't lock a bike, only a dock. Maybe we just need an indicator on the dock page to show whether its locked or not.

**Comment by jcurtiss** [comment]
We could change it back to damaged on the bike page like we originally had? And do docks have an attribute that we could use to lock them?

**Comment by daotoo** [comment]
docks have a `status` boolean property. So if we lock a bike, which ever dock has that bike and have it status switched to false??

**Comment by jeremycurtiss-wf** [comment]
@seancavanaugh I have updated the locking of bikes to use a modal instead of the confirm. It is deployed. I think it makes sense that docks would lock but I think we also we want to be able to lock or 'freeze' bikes for maintenance

**Comment by seancavanaugh** [comment]
@jcurtiss That makes sense, I think we should do that.

**Comment by jcurtiss** [comment]
K, I will add that dock functionality with the pull request for editing bikes/docks.

:+1: for merging this one

**Comment by seancavanaugh** [comment]
+1

**Comment by jcurtiss** [comment]
does https://github.com/ISUBikeShare/WebInterface/pull/37 need to be merged before this one?

**Comment by seancavanaugh** [comment]
No, this can go asap. I believe @daotoo  is currently adding additional tests to #37

**Comment by jcurtiss** [comment]
Okay i was confused because the other one is set to be merged into this branch

**Comment by seancavanaugh** [comment]
I probably goofed. Don't worry about it.

**Comment by daotoo** [comment]
+1 Merging

**Pull request merged**
